# Generated by Django 4.2.6 on 2024-02-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('AilmentID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AilmentName', models.CharField(max_length=100)),
                ('AilmentDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('HospitalName', models.CharField(max_length=100)),
                ('hospitalType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostelAsset',
            fields=[
                ('AssetID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AssetName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('AvailabilityStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('MedicineID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
                ('Uses', models.CharField(max_length=100)),
                ('SideEffects', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NecessityStoreItem',
            fields=[
                ('ItemID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemDescription', models.CharField(max_length=100)),
                ('ItemPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FloorNumber', models.CharField(max_length=100)),
                ('RoomNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('RegistrationNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('RoomId', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('DateOfJoining', models.DateTimeField()),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateTimeField()),
                ('EmailID', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('roomLeader', models.BooleanField()),
                ('adminName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.admin')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoomLeader',
            fields=[
                ('RoomLeaderID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('RegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ReservationDate', models.DateTimeField()),
                ('AssetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.hostelasset')),
                ('RegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('OrderDate', models.DateTimeField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.necessitystoreitem')),
                ('RegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalVisit',
            fields=[
                ('VisitID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Purpose', models.CharField(max_length=100)),
                ('VisitDate', models.DateTimeField()),
                ('HospitalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.hospital')),
                ('RegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student')),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('healthId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('AilmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.ailment')),
                ('RegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student')),
                ('VisitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.hospitalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilePhone', models.BooleanField()),
                ('laptop', models.BooleanField()),
                ('earphone', models.BooleanField()),
                ('kindle', models.BooleanField()),
                ('RegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='HospitalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.hospital'),
        ),
        migrations.AddField(
            model_name='ailment',
            name='MedicineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.medicine'),
        ),
    ]
