# Generated by Django 4.2.6 on 2024-02-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adminName',
        ),
    ]
