# Generated by Django 4.2.6 on 2024-02-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_remove_student_adminname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RoomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.room'),
        ),
    ]
