# Generated by Django 4.2.6 on 2024-02-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_alter_student_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='RoomId',
        ),
        migrations.AddField(
            model_name='room',
            name='RegistrationNumber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student'),
            preserve_default=False,
        ),
    ]
