# Generated by Django 4.2.6 on 2024-02-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_remove_student_roomid_room_registrationnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='RegistrationNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='userName',
        ),
        migrations.AddField(
            model_name='user',
            name='RegistrationNumber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student'),
            preserve_default=False,
        ),
    ]
