# Generated by Django 4.2.6 on 2024-02-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_remove_room_registrationnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Year',
        ),
    ]
