# Generated by Django 4.2.6 on 2024-02-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0006_remove_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='RegistrationNumber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.student'),
            preserve_default=False,
        ),
    ]
