# Generated by Django 4.2.6 on 2024-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0007_room_registrationnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessitystoreitem',
            name='ItemImage',
            field=models.ImageField(default=None, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
