# Generated by Django 4.2.6 on 2024-03-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0008_necessitystoreitem_itemimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='RegistrationNumber',
        ),
        migrations.AddField(
            model_name='roomleader',
            name='FloorNumber',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomleader',
            name='RoomNumber',
            field=models.IntegerField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
