# Generated by Django 4.2.6 on 2024-03-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0012_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='userName',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
