# Generated by Django 4.2.6 on 2024-03-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0013_remove_student_username_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.user'),
            preserve_default=False,
        ),
    ]
