# Generated by Django 4.2.6 on 2024-03-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0016_user_id_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_superuser',
        ),
    ]
