# Generated by Django 4.2.6 on 2024-03-06 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0019_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='userName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
