# Generated by Django 4.2.6 on 2024-03-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0020_alter_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='userName',
            new_name='username',
        ),
    ]
