# Generated by Django 4.2.6 on 2024-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0028_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
