# Generated by Django 4.2.6 on 2024-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0034_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roomLeader',
        ),
        migrations.AddField(
            model_name='room',
            name='roomLeader',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomLeader',
        ),
    ]
