# Generated by Django 4.2.6 on 2024-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0039_alter_room_roomleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='MobileNumber',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='EmailID',
            field=models.EmailField(max_length=100),
        ),
    ]
